# Generated by Django 5.0.2 on 2024-02-14 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Examiner",
        ),
    ]
