# Generated by Django 5.0.2 on 2024-02-14 23:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_user_examiner"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentGroup",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.TextField()),
                ("end_active_date", models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="examiner",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="examiner",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="examiner",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="examiner",
            name="docgrp",
            field=models.ManyToManyField(to="api.documentgroup"),
        ),
    ]
