# Generated by Django 5.0.2 on 2024-02-14 23:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_documentgroup_alter_examiner_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.TextField()),
                ("metadata", models.TextField()),
                ("uintarray", models.TextField()),
                (
                    "docgrp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.documentgroup",
                    ),
                ),
            ],
        ),
    ]
